# Generated by Django 6.0 on 2025-12-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_review_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
